# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bproto.proto\"(\n\nParameters\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"B\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05label\x18\x02 \x01(\t\x12\x1f\n\nparameters\x18\x03 \x03(\x0b\x32\x0b.Parameters\"&\n\x04\x45\x64ge\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\"V\n\x07Network\x12\x14\n\x05nodes\x18\x01 \x03(\x0b\x32\x05.Node\x12\x14\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x05.Edge\x12\x1f\n\nparameters\x18\x03 \x03(\x0b\x32\x0b.Parameters\"Q\n\rNetworkResult\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1f\n\nparameters\x18\x03 \x03(\x0b\x32\x0b.Parameters25\n\x07Trainer\x12*\n\x0cTrainNetwork\x12\x08.Network\x1a\x0e.NetworkResult\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PARAMETERS']._serialized_start=15
  _globals['_PARAMETERS']._serialized_end=55
  _globals['_NODE']._serialized_start=57
  _globals['_NODE']._serialized_end=123
  _globals['_EDGE']._serialized_start=125
  _globals['_EDGE']._serialized_end=163
  _globals['_NETWORK']._serialized_start=165
  _globals['_NETWORK']._serialized_end=251
  _globals['_NETWORKRESULT']._serialized_start=253
  _globals['_NETWORKRESULT']._serialized_end=334
  _globals['_TRAINER']._serialized_start=336
  _globals['_TRAINER']._serialized_end=389
# @@protoc_insertion_point(module_scope)
